### ISSUE TITLE
Addition of mcl-wasm compatible serialisation

### ISSUE THREAD

**Issue by sumo** [adjoint-io/pairing#6]
I am looking at adding in mcl-wasm specific serialisation support. Was going to add it to master but seems like there has been plenty of work on galois-field-integration branch. If you are looking to merge this into master, I'll make my changes based on the galois-field-integration branch. I'm in no rush, so happy to track a development branch and reduce my merge effort. What's the preference?

**Comment by sdiehl** [comment]
The `galois-field-integration` branch will be merged shortly and we'll cut a new major version of pairing for it. If you're looking to add new serialsiation support to this library probably best to base it on top of the galois field branch.

**Comment by sumo** [comment]
Thanks will do.
